### ISSUE TITLE
Incorrect info

### ISSUE THREAD

**Issue by iamclaytonray** [LambdaSchool/C-Web-Server#122]
The following section in the readme is incorrect. While you can use GET to request an HTML document, that is not necessarily a common use-case. A more common use-case for GET is to request data from a server and send that back in the response payload, typically using JSON. I think this description limits students to a box of what GET is for and is very inaccurate. Imagine someone interviewing for a company and them saying something like that. That really hurts someone's chances of nailing that job they really want, and need since they just spent $10k+ on this program.

> A web server is a piece of software that accepts HTTP requests (commonly GET
> requests for HTML pages), and returns responses (commonly HTML pages). Other
> common uses are GET requests for images within web pages, and POST requests to
> upload data to the server (e.g. a form submission or file upload).

**Comment by beejjorgensen** [comment]
By the time our students get to this lesson, they have been writing server code to handle GET requests and return JSON data for months. It's unlikely they will forget that when presented with this README.

The text was ambiguous. The intent of the writing was that HTML pages were commonly retrieved with GET requests (which is certainly true), not that GET requests were primarily used to retrieve HTML.

You did get me wonder what the breakdown of GET requests by Content-Type was. It's a hard thing to Google, though. Glancing at Reuters, the XHR is about neck and neck with the HTML. The big winner overall, though, is images. Tons of those. Of course, it depends on the site entirely.

Thank you for the suggestion; I'll add some clarification.
